import type { Theme, ThemeId } from '@/types/voxlog'

export const THEMES: Record<ThemeId, Theme> = {
  white: {
    id: 'white',
    nameZh: '纯白',
    nameEn: 'Pure White',
    bg: '#F9F9F6',
    text: '#1A1A1A',
    secondary: '#4A4A4A',
    accent: '#D97757',
    border: '#E5E5E0',
    inputBg: '#FFFFFF',
    cardBg: '#FFFFFF',
    mutedText: '#9A9A9A',
  },
  black: {
    id: 'black',
    nameZh: '纯黑',
    nameEn: 'Pure Black',
    bg: '#0F0F0F',
    text: '#F0F0F0',
    secondary: '#C0C0C0',
    accent: '#D97757',
    border: '#2C2C2C',
    inputBg: '#1A1A1A',
    cardBg: '#1A1A1A',
    mutedText: '#707070',
  },
  gray: {
    id: 'gray',
    nameZh: '浅灰',
    nameEn: 'Light Gray',
    bg: '#F2F2F2',
    text: '#2C2C2C',
    secondary: '#555555',
    accent: '#D97757',
    border: '#DDDDDD',
    inputBg: '#FAFAFA',
    cardBg: '#FAFAFA',
    mutedText: '#999999',
  },
  blue: {
    id: 'blue',
    nameZh: '雾霾蓝',
    nameEn: 'Misty Blue',
    bg: '#E8EEF4',
    text: '#1A2A3A',
    secondary: '#3A5A7A',
    accent: '#4A7FA8',
    border: '#C5D5E5',
    inputBg: '#F0F5FA',
    cardBg: '#F0F5FA',
    mutedText: '#7A9AB8',
  },
  mint: {
    id: 'mint',
    nameZh: '薄荷绿',
    nameEn: 'Mint Green',
    bg: '#E8F5EE',
    text: '#1A3A2A',
    secondary: '#2A6A4A',
    accent: '#3A9A6A',
    border: '#C0E0D0',
    inputBg: '#F0FAF4',
    cardBg: '#F0FAF4',
    mutedText: '#6AA888',
  },
  pink: {
    id: 'pink',
    nameZh: '樱花粉',
    nameEn: 'Sakura Pink',
    bg: '#FDF0F5',
    text: '#3A1A2A',
    secondary: '#7A3A5A',
    accent: '#C8507A',
    border: '#F0D0DC',
    inputBg: '#FFF5F8',
    cardBg: '#FFF5F8',
    mutedText: '#B088A0',
  },
  purple: {
    id: 'purple',
    nameZh: '香芋紫',
    nameEn: 'Taro Purple',
    bg: '#F0EAF8',
    text: '#2A1A4A',
    secondary: '#5A3A8A',
    accent: '#8A5AC0',
    border: '#D8C8F0',
    inputBg: '#F8F2FF',
    cardBg: '#F8F2FF',
    mutedText: '#9878C0',
  },
}

export const MEMBER_LIMITS = {
  free: { dailyAiCount: 3 },
  standard: { dailyAiCount: 10 },
  pro: { dailyAiCount: 30 },
}

export const MEMBER_NAMES = {
  free: { zh: '免费版', en: 'Free' },
  standard: { zh: '标准会员', en: 'Standard' },
  pro: { zh: 'Pro 会员', en: 'Pro' },
}

export const DEFAULT_CONFIG = {
  theme: 'white' as ThemeId,
  language: 'zh' as const,
  memberLevel: 'free' as const,
  memberExpiresAt: -1,          // -1 = 未激活
  deviceId: '',                 // 启动时生成
  reminderEnabled: false,
  customApiKey: '',
  customBaseUrl: '',
  customModel: '',
  dailyAiCount: {},
}
